### ISSUE TITLE
non-unique and blank keywords are able to come through on import

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/imports#17]
I **think** this is the case. 
I don't know how else they would have gotten in other than through an import process.
This was discovered when attempting to submit an article after an update and is described here https://github.com/BirkbeckCTP/janeway/issues/2306
and further discussed on the cmu channel on discord.

but when importing there appears to be a way that blank keywords  get in to the keyword table. 

Here is an example of a line from the csv we used for import:
```
Article identifier, Article title,Section Name, Volume number, Issue number, Subtitle, Abstract, publication stage, keywords, date/time accepted, date/time publishded , DOI, Author Salutation, Author first name,Author Middle Name, Author last name, Author Institution, Biography, Author Email, Is Corporate (Y/N), PDF URI,XML URI, HTML URI, Figures URI (zip)
736,"Turning Points in Negotiation",Articles,4,1,,"",Published,"",2011-01-07T00:00:00,2011-01-07T00:00:00,10.1111/j.1750-4716.2010.00068.x,,Daniel,,Druckman,,"",,N,file:///home/jon/clients/cmu/janeway/ncmrwiley/NCMR68/j.1750-4716.2010.00068.x.pdf,,,
```
you can see that we still had the "" in the keywords row. that is probably how they got in, so that's kind of our fault, but there should be some check for this.
Let me know if you'd like more description or to see any of our other materials or would like me to check anything else.

**Comment by mauromsl** [comment]
Fixed by d2cb9c4383fe661f91a2cfc3334ff39bc2af58fa
