### ISSUE TITLE
Required Agreement field not populated on import

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/imports#29]
The Update Article workflow doesn't provide articles any text for Agreement, which is a required field. This causes issues when changing stages manually via the admin interface.

Either the Agreement field needs to be made optional, or something needs to be provided to that field in lieu of an agreement.

**Comment by ajrbyers** [comment]
Have previously suggested setting it to “Imported Article”

**Comment by joemull** [comment]
I like it. Would you add a column in the template, or would you just set that text using the logic?

**Comment by joemull** [comment]
Resolved via #48
