### ISSUE TITLE
Handle YYYY-MM-DD better in IEU

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/imports#34]
Right now the importer complains about 'naive' DateTime objects because content is often imported with `YYYY-MM-DD` in those fields. We can make it append ` 00:00:00+00:00` on these. This also could be used on the issue pub date field (see also https://github.com/BirkbeckCTP/janeway/issues/2579).

**Comment by ajrbyers** [comment]
Better yet, use make_aware.

**Comment by joemull** [comment]
Resolved via #48
